// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeod2CgKMceqHDm9ZFZw6WJxSpc2PQNHU',
    appId: '1:534178575531:web:61cd4eb202ba78e41a73ee',
    messagingSenderId: '534178575531',
    projectId: 'taskmanagement-22ac3',
    authDomain: 'taskmanagement-22ac3.firebaseapp.com',
    storageBucket: 'taskmanagement-22ac3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYP59DmQDpKAFntgfg3g2gFRHNSYLzNpM',
    appId: '1:534178575531:android:4522d7dbc6565ebf1a73ee',
    messagingSenderId: '534178575531',
    projectId: 'taskmanagement-22ac3',
    storageBucket: 'taskmanagement-22ac3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPUQF8-iBXjWQHgrgllbtTWAAM4pCZSgg',
    appId: '1:534178575531:ios:6f99fa56472a09531a73ee',
    messagingSenderId: '534178575531',
    projectId: 'taskmanagement-22ac3',
    storageBucket: 'taskmanagement-22ac3.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementCw06',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPUQF8-iBXjWQHgrgllbtTWAAM4pCZSgg',
    appId: '1:534178575531:ios:6f99fa56472a09531a73ee',
    messagingSenderId: '534178575531',
    projectId: 'taskmanagement-22ac3',
    storageBucket: 'taskmanagement-22ac3.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementCw06',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeod2CgKMceqHDm9ZFZw6WJxSpc2PQNHU',
    appId: '1:534178575531:web:a5e3248be188be431a73ee',
    messagingSenderId: '534178575531',
    projectId: 'taskmanagement-22ac3',
    authDomain: 'taskmanagement-22ac3.firebaseapp.com',
    storageBucket: 'taskmanagement-22ac3.firebasestorage.app',
  );
}
